# Generated by Django 5.0.7 on 2024-07-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_auto_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='cantidad_pasajeros',
            new_name='cant_pasajeros',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='genero',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='combustible',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='id_auto',
            field=models.CharField(max_length=20),
        ),
    ]
